#!/bin/bash
echo "                                          "
echo "                                          "
echo "    (  )   (   )  )                       "
echo "     ) (   )  (  (                        "
echo "     ( )  (    ) )                        "
echo "     _____________                        "
echo "    <_____________> ___                   "
echo "    |             |/ _ \                  "
echo "    |               | | |                 "
echo "    |               |_| |                 "
echo " ___|             |\___/                  "
echo "/    \___________/    \                   "
echo "\_____________________/                   "
echo "                                          "
echo " teash - a simple tea timer for your shell"
echo "                                          "
echo " Earl Grey: 3-5 minutes                   "
echo "                                          "
echo -n "How long to draw (minutes)? [ENTER]:   "
read selection
echo zZzZZZzz $selection minutes
time=$(($selection * 60))
$(STEEP=$time; sleep $time; xmessage "Your tea is done") &
